import sys
import os
from datetime import datetime

import streamlit as st

if "chat_history" not in st.session_state:
    st.session_state["chat_history"] = []

if "latest_report" not in st.session_state:
    st.session_state["latest_report"] = None

if "latest_route" not in st.session_state:
    st.session_state["latest_route"] = "Unknown"

if "latest_sources" not in st.session_state:
    st.session_state["latest_sources"] = []

if "latest_time" not in st.session_state:
    st.session_state["latest_time"] = 0

if "insights" not in st.session_state:
    st.session_state["insights"] = ""

sys.path.append(
    os.path.dirname(
        os.path.dirname(
            os.path.abspath(__file__)
        )
    )
)

from agents.chat_agent import (
    chat_with_report
)

from graph import graph

from memory.database import (
    get_history,
    get_report_by_id
)


from io import BytesIO

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors



def generate_pdf(text, insights):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer
    )

    styles = getSampleStyleSheet()

    content = []

    # -----------------
    # TITLE
    # -----------------

    # -----------------
    # # INSIGHTS SECTION
    # # -----------------
    
    content.append(
        Paragraph(
            "Research Insights",
            styles["Heading1"]
        )
    )
    
    content.append(
        Paragraph(
            f"Confidence Score: {int(insights.get('confidence_score', 0) * 100)}%",
            styles["BodyText"]
        )
    )
    
    content.append(
        Paragraph(
            f"Source Quality: {int(insights.get('source_quality', 0) * 100)}%",
            styles["BodyText"]
        )
    )
    
    content.append(
        Paragraph(
            f"Coverage: {int(insights.get('coverage_score', 0) * 100)}%",
            styles["BodyText"]
        )
    )
    
    content.append(
        Paragraph(
            "Research Gaps",
            styles["Heading2"]
        )
    )
    
    for gap in insights.get("research_gaps", []):
        content.append(
            Paragraph(
                f"• {gap}",
                styles["BodyText"]
            )
        )
        
    content.append(
        Paragraph(
            "Contradictions",
            styles["Heading2"]
        )
    )
    
    contradictions = insights.get(
    "contradictions",
    []
    )
    
    if contradictions:
        for item in contradictions:
            content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )
    else:
        content.append(
            Paragraph(
            "None",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            "ResearchPilot AI",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "Autonomous Research Report",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(
            1,
            20
        )
    )

    # -----------------
    # REPORT BODY
    # -----------------

    lines = text.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        # markdown headings

        if line.startswith("# "):

            content.append(
                Spacer(
                    1,
                    10
                )
            )

            content.append(
                Paragraph(
                    line.replace(
                        "# ",
                        ""
                    ),
                    styles["Heading1"]
                )
            )

        elif line.startswith("## "):

            content.append(
                Paragraph(
                    line.replace(
                        "## ",
                        ""
                    ),
                    styles["Heading2"]
                )
            )

        elif line.startswith("### "):

            content.append(
                Paragraph(
                    line.replace(
                        "### ",
                        ""
                    ),
                    styles["Heading3"]
                )
            )

        else:

            content.append(
                Paragraph(
                    line,
                    styles["BodyText"]
                )
            )

        content.append(
            Spacer(
                1,
                4
            )
        )

        content.append(
            Paragraph(
            "Generated by ResearchPilot AI",
            styles["Italic"]
            )
        )

    # -----------------
    # FOOTER
    # -----------------

    content.append(
        Spacer(
            1,
            20
        )
    )

    content.append(
        Paragraph(
            "Generated by ResearchPilot AI",
            styles["Italic"]
        )
    )

    doc.build(
        content
    )

    buffer.seek(0)

    return buffer

# ----------------------------
# PAGE CONFIG
# ----------------------------

st.set_page_config(
    page_title="ResearchPilot AI",
    page_icon="🔬",
    layout="wide"
)

st.markdown("""
<style>

/* Main background */
.stApp {
    background: linear-gradient(
        135deg,
        #0f172a,
        #111827,
        #1e293b
    );
}

/* Titles */
h1, h2, h3 {
    color: white !important;
}

/* Glass cards */
[data-testid="metric-container"] {
    background: rgba(255,255,255,0.08);
    border: 1px solid rgba(255,255,255,0.15);
    padding: 20px;
    border-radius: 18px;
    backdrop-filter: blur(12px);
}

/* Buttons */
.stButton button {
    width: 100%;
    border-radius: 12px;
    height: 50px;
    font-weight: bold;
    border: none;
}

/* Text input */
.stTextInput input {
    border-radius: 12px;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background-color: #111827;
}

/* Report container */
.report-card {
    background: rgba(255,255,255,0.06);
    padding: 25px;
    border-radius: 20px;
    border: 1px solid rgba(255,255,255,0.12);
    margin-top: 20px;
}

</style>
""", unsafe_allow_html=True)

# ----------------------------
# SESSION STATE
# ----------------------------

if "agent_status" not in st.session_state:

    st.session_state.agent_status = {
        "Router Agent": "⏳ Waiting",
        "Reader Agent": "⏳ Waiting",
        "Research Agent": "⏳ Waiting",
        "Critic Agent": "⏳ Waiting",
        "Writer Agent": "⏳ Waiting"
    }

# ----------------------------
# PAGE HEADER
# ----------------------------

st.markdown("""
<h1 style='text-align:center; font-size:60px;'>
🔬 ResearchPilot AI
</h1>

<p style='text-align:center;
font-size:20px;
color:#cbd5e1;'>
Autonomous Multi-Agent Research Platform
</p>
""", unsafe_allow_html=True)

# ----------------------------
# SIDEBAR
# ----------------------------

with st.sidebar:

    st.header("⚙️ System Status")

    for agent, status in st.session_state.agent_status.items():

        st.write(
            f"{status} {agent}"
        )

    st.divider()

    history = get_history()

    st.metric(
        "📊 Reports Generated",
        len(history)
    )

    st.divider()

    st.header("📚 Research History")

    if history:

        for item in history[:10]:

            report_id = item[0]
            query_text = item[1]

            if st.button(
                query_text,
                key=f"history_{report_id}"
            ):

                st.session_state[
                    "selected_report"
                ] = report_id

                st.rerun()

    else:

        st.info(
            "No previous research yet."
        )

# ----------------------------
# DISPLAY SAVED REPORT
# ----------------------------

if "selected_report" in st.session_state:

    report = get_report_by_id(
        st.session_state[
            "selected_report"
        ]
    )

    if report:

        st.subheader(
            f"📄 {report[1]}"
        )

        st.markdown(
            report[3]
        )

        st.divider()

# ----------------------------
# QUERY INPUT
# ----------------------------

query = st.text_input(
    "Enter Research Topic",
    placeholder="Example: Latest developments in RAG"
)



# ----------------------------
# GENERATE REPORT
# ----------------------------

if st.button("🚀 Generate Report"):

    if query.strip() == "":

        st.warning(
            "Please enter a research topic."
        )

        st.stop()

    progress = st.progress(0)

    with st.spinner(
        "Running Multi-Agent Workflow..."
    ):

        start_time = datetime.now()

        st.session_state.agent_status[
            "Router Agent"
        ] = "🔄 Running"

        progress.progress(20)

        result = graph.invoke(
            {
                "query": query
            }
        )

        end_time = datetime.now()

        for agent in st.session_state.agent_status:

            st.session_state.agent_status[
                agent
            ] = "✅ Complete"

        progress.progress(100)

        st.session_state[
            "latest_report"
        ] = result["formatted_report"]

        st.session_state[
            "latest_route"
        ] = result.get(
            "route",
            "Unknown"
        )

        st.session_state[
            "latest_sources"
        ] = result.get(
            "sources",
            []
        )

        st.session_state[
            "latest_time"
        ] = (
            end_time - start_time
        ).seconds

        st.session_state[
            "insights"
        ] = result.get(
             "insights",
             ""
        )
        
        st.rerun()


# ----------------------------
# REPORT DISPLAY
# ----------------------------

if st.session_state.get(
    "latest_report"
):

    st.divider()

    insights = st.session_state.get(
    "insights",
    {}
    )

    c1, c2, c3 = st.columns(3)
    with c1:
        st.metric(
        "Confidence",
        f"{int(insights.get('confidence_score',0)*100)}%"
    )
        
    with c2:
        st.metric(
        "Source Quality",
        f"{int(insights.get('source_quality',0)*100)}%"
    )
        
    with c3:
        st.metric(
        "Coverage",
        f"{int(insights.get('coverage_score',0)*100)}%"
    )

    #st.info(f"📄 Words: {word_count} | "f"🔗 Sources: {len(st.session_state['latest_sources'])} | "f"⏱️ Generated in: {st.session_state['latest_time']}s")

    st.divider()

    with st.container():
        st.markdown(
        st.session_state["latest_report"]
    )

    if st.session_state.get(
    "insights"
):
        st.divider()

    insights = st.session_state.get(
    "insights",
    ""
    )

    st.subheader(
        "📄 Research Report"
    )
        
    with st.expander(
        "🔍 Research Gaps",
        expanded=True
    ):
        gaps = insights.get(
            "research_gaps",
            []
        )
        
        if gaps:

            for gap in gaps:
                st.write(
                    f"• {gap}"
            )
        else:
            st.write(
                "No major gaps identified."
        )
        
    with st.expander(
        "⚠️ Contradictions",
        expanded=False
    ):
        contradictions = insights.get(
            "contradictions",
            []
            )
        
        if contradictions:
            for item in contradictions:
                st.write(
                    f"• {item}"
                )
        else:
            st.write(
                "No contradictions found."
            )
  
    st.subheader(
        "🧠 Research Insights"
    )
    
    if st.session_state["latest_sources"]:
            st.divider()
            st.subheader(
                "🔗 Sources Used"
            )

    for source in st.session_state["latest_sources"]:
        st.markdown(
        f"- [{source}]({source})"
    )

    col1, col2 = st.columns(2)

    with col1:

        st.download_button(
            label="⬇️ Download Markdown",
            data=st.session_state[
                "latest_report"
            ],
            file_name="research_report.md",
            mime="text/markdown"
        )

    with col2:
        
        try:
            
            pdf_file = generate_pdf(
                st.session_state["latest_report"],
                st.session_state["insights"]
            )
            
            st.download_button(
            label="📄 Download PDF",
            data=pdf_file,
            file_name="research_report.pdf",
            mime="application/pdf"
            )
            
        except Exception as e:
            st.error(
            f"PDF Error: {e}"
        )


report_text = (
    st.session_state[
        "latest_report"
    ] or ""
)

word_count = len(
    report_text.split()
)

st.info(
    f"📄 Words: {word_count} | "
    f"🔗 Sources: {len(st.session_state['latest_sources'])} | "
    f"⏱️ Generated in: {st.session_state['latest_time']}s"
)



# ----------------------------
# FOLLOW-UP CHAT
# ----------------------------

if st.session_state.get(
    "latest_report"
):

    st.divider()

    st.subheader(
        "💬 Ask Follow-up Questions"
    )

    follow_up = st.text_input(
        "Ask about this report",
        key="follow_up"
    )

    if st.button(
        "Send",
        key="send_followup"
    ):

        if follow_up.strip():

            answer = chat_with_report(
                st.session_state[
                    "latest_report"
                ],
                follow_up,
                st.session_state[
                    "chat_history"
                ]
            )

            st.session_state[
                "chat_history"
            ].append(
                {
                    "question": follow_up,
                    "answer": answer
                }
            )
            st.rerun()

    for chat in st.session_state[
        "chat_history"
    ]:

        with st.chat_message(
            "user"
        ):
            st.write(
                chat["question"]
            )

        with st.chat_message(
            "assistant"
        ):
            st.write(
                chat["answer"]
            )


# ----------------------------
# CONTINUE RESEARCH
# ----------------------------

if st.session_state.get(
    "latest_report"
):

    st.divider()

    st.subheader(
        "🔍 Continue Research"
    )

    deeper_query = st.text_input(
        "Explore a specific aspect",
        key="continue_research"
    )

    if st.button(
        "Continue Research"
    ):

        if deeper_query.strip():

            enhanced_query = f"""
Original Report:

{st.session_state['latest_report'][:3000]}

Further Research Request:

{deeper_query}
"""

            with st.spinner(
                "Expanding research..."
            ):

                result = graph.invoke(
                    {
                        "query": enhanced_query
                    }
                )

            st.session_state[
                "latest_report"
            ] = result[
                "formatted_report"
            ]

            st.session_state[
                "insights"
            ] = result.get(
                "insights",
                ""
            )
            
            st.rerun()